"""
Server-side license key generation and HMAC validation.

Keys are 16 uppercase hex characters stored WITHOUT hyphens in the database,
but displayed to customers as XXXX-XXXX-XXXX-XXXX.

Structure:
  First 8 chars  = cryptographically random payload
  Last  8 chars  = HMAC-SHA256(SECRET, payload)[:8]

The HMAC is a fast client-side sanity check. The authoritative check is
always the database lookup (was this key actually sold?).
"""

import hashlib
import hmac
import os
import secrets

# Must match _LIC_SECRET in process_photos.py and installer/keygen.py
_SECRET: bytes = os.environ.get(
    "LICENSE_HMAC_SECRET", "PhotoGeoTager-mjs-2025#kX9mRv7"
).encode()


def generate_key() -> str:
    """
    Generate one random valid key.
    Returns the bare 16-char form (no hyphens) for DB storage.
    Use format_key() to display it to the customer.
    """
    payload  = secrets.token_hex(4).upper()   # 8 random hex chars
    sig      = hmac.new(_SECRET, payload.encode(),
                        hashlib.sha256).hexdigest()[:8].upper()
    return payload + sig                       # 16 chars, no hyphens


def format_key(raw: str) -> str:
    """ABCDEF012345ABCD  →  ABCD-EF01-2345-ABCD"""
    k = raw.upper().replace("-", "")
    return f"{k[0:4]}-{k[4:8]}-{k[8:12]}-{k[12:16]}"


def normalise_key(key: str) -> str:
    """Strip hyphens/spaces and upper-case for DB lookups."""
    return key.strip().upper().replace("-", "").replace(" ", "")


def validate_key_hmac(key: str) -> bool:
    """
    Quick offline HMAC check. Returns False for keys that could not have
    been generated by us, saving a DB round-trip. NOT a substitute for
    the full DB activation lookup.
    """
    k = normalise_key(key)
    if len(k) != 16:
        return False
    payload  = k[:8]
    expected = hmac.new(_SECRET, payload.encode(),
                        hashlib.sha256).hexdigest()[:8].upper()
    return hmac.compare_digest(k[8:], expected)
